### ISSUE TITLE
Order Add Note Action does not show any Input fields in the automation backend

### ISSUE THREAD

**Issue by Stoffpalast** [shopmagic/shopmagic-example#1]
The example plugin contains an example action: Order Add Note. 
Usually, when you are in the automation backend in WP and choose an action, the related input fields show up.
I.e. when choosing the Send Email action, the Fields Description, Delay, To, BCC, Subject, and so on show up so the admin can enter the desired settings to configure this action.

With the example plugin, the new option "Add Order Note " shows up as an action, but when selected in the drop-down, not related input fields show up. This makes it impossible to configure this action.

Is this something the example plugin is missing on purpose?
Is it a bug?
It would help, if your example code would be fully functional, s one can understand where to define specific input fields to appear in the backend for custom actions.

**Comment by dyszczo** [comment]
@Stoffpalast Thanks for your report. 
One of the changes in the ShopMagic validation subroutine has created a problem in this plugin. And as we are not testing this plugin with each release, the bug was undetected till now. It should now be fixed 👍
